-- AlterTable
ALTER TABLE "progress" ADD COLUMN "commonShards" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "progress" ADD COLUMN "rareShards" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "progress" ADD COLUMN "epicShards" INTEGER NOT NULL DEFAULT 0;
