export type NavTab = "Home" | "Game" | "Pets" | "Bag" | "Shop" | "More";

/** Every destination in the app — mirrors the reference bundle's "Phần 1..6" screens. */
export type Screen =
  | "onboarding"
  | "login"
  | "createChild"
  | "home"
  | "lesson"
  | "shop"
  | "gameHub"
  | "miniGame"
  | "parentArea"
  | "petCare"
  | "topics"
  | "srsCard"
  | "bag"
  | "profile"
  | "premium"
  | "notifications"
  | "wordCatch"
  | "flappyDragon"
  | "englishShop"
  | "englishHome"
  | "wordRpg"
  | "wordTrain"
  | "englishDetective"
  | "echoParrot"
  | "chatBuddy"
  | "systemStates"
  | "rank"
  | "questStreak"
  | "story"
  | "settings"
  | "petCollection"
  | "petRanch"
  | "myContent"
  | "fightRoom"
  | "dictionary"
  | "worldLessons"
  | "battlePass"
  | "more";
