import { useState } from "react";
import { ArrowLeft, FileText, Mail, ShieldCheck } from "lucide-react";
import { LEGAL_CONTACT_EMAIL, LEGAL_EFFECTIVE_DATE, LEGAL_ENTITY, type LegalKind } from "../lib/legal";
import { useLang } from "../lib/i18n";

type LegalSection = { title: string; paragraphs: string[]; bullets?: string[] };

const PRIVACY_VI: LegalSection[] = [
  { title: "1. Ai vận hành PetLingo", paragraphs: [`${LEGAL_ENTITY} ("PetLingo", "chúng tôi") cung cấp ứng dụng học tiếng Anh có thú cưng ảo dành cho gia đình. Tài khoản chính phải do phụ huynh hoặc người giám hộ tạo và quản lý.`] },
  { title: "2. Dữ liệu chúng tôi thu thập", paragraphs: ["Chúng tôi giới hạn dữ liệu ở mức cần thiết để vận hành trò chơi và lưu tiến độ."], bullets: ["Tài khoản phụ huynh: email, số điện thoại nếu tự nguyện cung cấp, mã định danh đăng nhập Google/Apple/Facebook nếu dùng đăng nhập xã hội.", "Hồ sơ trẻ: tên gọi trong app, năm sinh (không lưu ngày sinh đầy đủ), avatar và mã kết bạn.", "Hoạt động học và chơi: câu trả lời, từ đã học/lưu, điểm, XP, coin/gem ảo, pet, vật phẩm, streak, nhiệm vụ và lịch sử phần thưởng.", "Tính năng bạn bè: lời mời, danh sách bạn đã chấp nhận, quà tặng và tên hiển thị cần thiết để ghé thăm trang trại.", "Dữ liệu kỹ thuật tối thiểu: thời điểm yêu cầu, lỗi và địa chỉ IP có thể xuất hiện trong nhật ký máy chủ vì mục đích bảo mật và vận hành."] },
  { title: "3. Micro và giọng nói", paragraphs: ["Echo Parrot chỉ bật micro sau khi người dùng chủ động cho phép. PetLingo dùng dịch vụ nhận dạng giọng nói của hệ điều hành hoặc trình duyệt để chuyển lời nói thành chữ; nhà cung cấp nền tảng có thể xử lý âm thanh theo chính sách của họ. PetLingo không lưu file ghi âm trên máy chủ của mình. Văn bản tiếng Anh dùng để phát âm có thể được gửi tới dịch vụ tổng hợp giọng nói của Microsoft; nội dung này không kèm hồ sơ trẻ." ] },
  { title: "4. Cách chúng tôi sử dụng dữ liệu", paragraphs: ["Dữ liệu được dùng để xác thực phụ huynh, tạo trải nghiệm học phù hợp, lưu tiến độ, vận hành bạn bè/quà tặng, bảo vệ tài khoản, hỗ trợ người dùng và tuân thủ nghĩa vụ pháp lý. Chúng tôi không bán dữ liệu cá nhân, không dùng quảng cáo hành vi và hiện không tích hợp SDK quảng cáo hoặc phân tích bên thứ ba."] },
  { title: "5. Chia sẻ và nhà cung cấp dịch vụ", paragraphs: ["Dữ liệu có thể được xử lý bởi nhà cung cấp hạ tầng lưu trữ/cơ sở dữ liệu và, khi phụ huynh chọn dùng, Google, Apple hoặc Facebook để đăng nhập. Chúng tôi chỉ chia sẻ khi cần cung cấp dịch vụ, bảo vệ người dùng, tuân thủ pháp luật hoặc có chỉ dẫn hợp lệ của phụ huynh. Bạn bè đã được chấp nhận chỉ thấy tên hiển thị, pet/trang trại và quà tặng liên quan; không thấy email hay năm sinh."] },
  { title: "6. Quyền của phụ huynh", paragraphs: ["Phụ huynh có thể xem và sửa hồ sơ trẻ, tắt hiển thị bảng xếp hạng, xoá từng hồ sơ hoặc xoá vĩnh viễn toàn bộ tài khoản trong Cài đặt. Việc xoá tài khoản xoá các hồ sơ trẻ và dữ liệu liên quan khỏi cơ sở dữ liệu hoạt động; bản sao lưu bảo mật có thể tồn tại trong thời gian giới hạn trước khi tự xoá. Phụ huynh cũng có thể yêu cầu truy cập, sửa, xuất hoặc ngừng thu thập qua email liên hệ bên dưới."] },
  { title: "7. Lưu giữ và bảo mật", paragraphs: ["Chúng tôi giữ dữ liệu trong thời gian tài khoản hoạt động hoặc khi cần cung cấp dịch vụ, giải quyết tranh chấp và đáp ứng luật áp dụng. Chúng tôi dùng kết nối HTTPS cho production, mật khẩu được băm và kiểm soát truy cập; tuy nhiên không hệ thống nào có thể đảm bảo an toàn tuyệt đối."] },
  { title: "8. Quyền riêng tư của trẻ em", paragraphs: ["Trẻ không tự tạo tài khoản bằng email. Phụ huynh phải xem thông báo này và đồng ý trước khi tạo hồ sơ trẻ. Nếu pháp luật tại nơi bạn sống yêu cầu một phương thức xác minh đồng ý cụ thể, PetLingo phải hoàn thành phương thức đó trước khi thu thập dữ liệu của trẻ. Hãy liên hệ ngay nếu bạn cho rằng dữ liệu trẻ đã được cung cấp khi chưa có thẩm quyền phù hợp."] },
  { title: "9. Thay đổi và liên hệ", paragraphs: [`Khi nội dung thay đổi đáng kể, chúng tôi sẽ cập nhật ngày hiệu lực và yêu cầu phụ huynh xác nhận lại khi cần. Liên hệ về quyền riêng tư: ${LEGAL_CONTACT_EMAIL}.`] },
];

const PRIVACY_EN: LegalSection[] = [
  { title: "1. Who operates PetLingo", paragraphs: [`${LEGAL_ENTITY} ("PetLingo", "we") provides a family-managed English-learning game with virtual pets. The primary account must be created and managed by a parent or legal guardian.`] },
  { title: "2. Data we collect", paragraphs: ["We limit collection to data needed to operate the service and save learning progress."], bullets: ["Parent account: email, optional phone number, and Google/Apple/Facebook identifiers when social sign-in is chosen.", "Child profile: in-app display name, birth year (not full birth date), avatar, and friend code.", "Learning and game activity: answers, learned/saved words, scores, XP, virtual currency, pets, items, streaks, quests, and reward history.", "Friend features: requests, accepted friendships, gifts, and display information needed for ranch visits.", "Minimal technical data: request times, errors, and IP addresses may appear in server logs for security and operations."] },
  { title: "3. Microphone and speech", paragraphs: ["Echo Parrot activates the microphone only after permission is granted. Operating-system or browser speech recognition converts speech to text, and the platform provider may process audio under its own policy. PetLingo does not store audio recordings on its servers. English text used for pronunciation may be sent to Microsoft speech synthesis without a child profile attached."] },
  { title: "4. How we use data", paragraphs: ["We use data to authenticate parents, personalize learning, save progress, operate friends and gifts, secure accounts, provide support, and meet legal obligations. We do not sell personal data, use behavioral advertising, or currently include third-party advertising or analytics SDKs."] },
  { title: "5. Sharing and processors", paragraphs: ["Infrastructure and database hosting providers may process data for us. Google, Apple, or Facebook process data when a parent chooses their sign-in service. We disclose data only to deliver the service, protect users, comply with law, or follow a valid parent instruction. Accepted friends can see a display name, pets/ranch, and relevant gifts—not email or birth year."] },
  { title: "6. Parent rights", paragraphs: ["Parents can review and edit child profiles, disable leaderboard visibility, delete a profile, or permanently delete the entire account in Settings. Account deletion removes child profiles and related data from the active database; protected backups may remain for a limited rotation period. Parents may also request access, correction, export, deletion, or an end to further collection using the contact below."] },
  { title: "7. Retention and security", paragraphs: ["We retain data while the account is active or as needed to provide the service, resolve disputes, and satisfy applicable law. Production connections use HTTPS, passwords are hashed, and access is controlled, but no system can guarantee absolute security."] },
  { title: "8. Children's privacy", paragraphs: ["Children do not create email accounts themselves. A parent must review this notice and consent before a child profile is created. Where applicable law requires a specific verifiable parental-consent method, PetLingo must complete that method before collecting the child's data. Contact us immediately if you believe child data was provided without proper authority."] },
  { title: "9. Changes and contact", paragraphs: [`For material changes, we will update the effective date and request renewed parent acknowledgement when appropriate. Privacy contact: ${LEGAL_CONTACT_EMAIL}.`] },
];

const TERMS_VI: LegalSection[] = [
  { title: "1. Chấp nhận điều khoản", paragraphs: [`Bằng cách tạo tài khoản hoặc dùng PetLingo, phụ huynh/người giám hộ đồng ý Điều khoản này và Chính sách quyền riêng tư thay mặt gia đình. Nếu không đồng ý, vui lòng không tạo hồ sơ trẻ.`] },
  { title: "2. Tài khoản và giám sát", paragraphs: ["Người tạo tài khoản xác nhận mình đủ tuổi ký kết và có quyền quản lý hồ sơ trẻ. Bạn chịu trách nhiệm bảo mật thông tin đăng nhập, giám sát việc sử dụng của trẻ và cung cấp thông tin chính xác. Hãy báo ngay nếu nghi ngờ tài khoản bị truy cập trái phép."] },
  { title: "3. Dịch vụ học tập", paragraphs: ["PetLingo hỗ trợ luyện tiếng Anh qua bài học và trò chơi; không thay thế giáo viên, chương trình được công nhận hoặc tư vấn chuyên môn. Kết quả học phụ thuộc từng người và không được bảo đảm."] },
  { title: "4. Hành vi được phép", paragraphs: ["Không được phá hoại dịch vụ, vượt qua biện pháp bảo mật, gian lận phần thưởng, tự động thu thập dữ liệu, mạo danh người khác, quấy rối người dùng hoặc đưa nội dung bất hợp pháp/không phù hợp với trẻ em vào phần nội dung tự tạo."] },
  { title: "5. Bạn bè và nội dung do gia đình tạo", paragraphs: ["Kết bạn cần mã chính xác và sự chấp nhận của bên kia. Phụ huynh chịu trách nhiệm với tên hiển thị và nội dung tự tạo của mình, đồng thời cấp cho PetLingo quyền kỹ thuật cần thiết để lưu và hiển thị nội dung đó trong dịch vụ. Có thể xoá nội dung vi phạm hoặc hạn chế tài khoản để bảo vệ trẻ em và cộng đồng."] },
  { title: "6. Pet, coin, gem và mua hàng", paragraphs: ["Pet, coin, gem và vật phẩm là quyền sử dụng ảo, không phải tiền thật, không có giá trị quy đổi và không được giao dịch bên ngoài PetLingo. Bản hiện tại chưa xử lý thanh toán thật; mọi gói thử nghiệm hoặc giá hiển thị không tạo giao dịch tiền thật. Trước khi bật mua hàng, chúng tôi sẽ áp dụng cơ chế thanh toán của cửa hàng ứng dụng, quyền khôi phục và parental gate phù hợp."] },
  { title: "7. Sở hữu trí tuệ", paragraphs: ["PetLingo, mã nguồn phát hành, giao diện, hình ảnh và nội dung hệ thống thuộc chủ sở hữu tương ứng và được pháp luật bảo vệ. Điều khoản chỉ cấp quyền cá nhân, có giới hạn, không độc quyền và có thể thu hồi để gia đình sử dụng ứng dụng."] },
  { title: "8. Tạm ngừng, chấm dứt và thay đổi", paragraphs: ["Bạn có thể ngừng dùng và xoá tài khoản bất kỳ lúc nào. Chúng tôi có thể hạn chế tài khoản vi phạm, gây rủi ro an toàn hoặc theo yêu cầu pháp luật, đồng thời cố gắng thông báo khi phù hợp. Tính năng có thể thay đổi để cải thiện an toàn, chất lượng hoặc tuân thủ."] },
  { title: "9. Trách nhiệm và luật áp dụng", paragraphs: ["Dịch vụ được cung cấp theo phạm vi pháp luật cho phép. Không nội dung nào loại trừ quyền bắt buộc của người tiêu dùng hoặc trách nhiệm không thể loại trừ theo luật nơi bạn sống. Luật và cơ chế giải quyết tranh chấp cụ thể cần được cập nhật theo pháp nhân phát hành trước khi phát hành thương mại."] },
  { title: "10. Liên hệ", paragraphs: [`Đơn vị cung cấp: ${LEGAL_ENTITY}. Email hỗ trợ: ${LEGAL_CONTACT_EMAIL}.`] },
];

const TERMS_EN: LegalSection[] = [
  { title: "1. Acceptance", paragraphs: ["By creating an account or using PetLingo, the parent or legal guardian accepts these Terms and the Privacy Policy for the family. Do not create a child profile if you do not agree."] },
  { title: "2. Accounts and supervision", paragraphs: ["The account creator confirms they are old enough to contract and authorized to manage the child profile. You are responsible for login security, supervising child use, and providing accurate information. Notify us promptly of suspected unauthorized access."] },
  { title: "3. Learning service", paragraphs: ["PetLingo supports English practice through lessons and games. It is not a substitute for a teacher, accredited curriculum, or professional advice. Individual learning results are not guaranteed."] },
  { title: "4. Acceptable use", paragraphs: ["Do not disrupt the service, bypass security, manipulate rewards, scrape data, impersonate others, harass users, or submit illegal or child-inappropriate material through family-created content tools."] },
  { title: "5. Friends and family content", paragraphs: ["Friendship requires an exact code and acceptance by the other account. Parents are responsible for display names and content they create and grant PetLingo the technical license needed to store and display that content within the service. We may remove unsafe content or restrict accounts to protect children and the community."] },
  { title: "6. Pets, coins, gems, and purchases", paragraphs: ["Pets, coins, gems, and items are limited virtual entitlements, not money, have no cash value, and may not be traded outside PetLingo. The current build does not process real payments; demo offers or displayed prices do not create a real-money transaction. Before purchases are enabled, we will implement store billing, restoration, and appropriate parental gates."] },
  { title: "7. Intellectual property", paragraphs: ["PetLingo software, interface, artwork, and system content belong to their respective owners and are protected by law. These Terms grant only a personal, limited, non-exclusive, revocable right to use the app."] },
  { title: "8. Suspension, termination, and changes", paragraphs: ["You may stop use and delete the account at any time. We may restrict unsafe, unlawful, or materially breaching accounts and will provide notice when appropriate. Features may change to improve safety, quality, or compliance."] },
  { title: "9. Liability and governing rules", paragraphs: ["The service is provided to the extent permitted by law. Nothing excludes mandatory consumer rights or liability that cannot legally be excluded where you live. The publishing entity must finalize governing-law and dispute terms before commercial release."] },
  { title: "10. Contact", paragraphs: [`Provider: ${LEGAL_ENTITY}. Support email: ${LEGAL_CONTACT_EMAIL}.`] },
];

export default function LegalDocument({ kind, onExit }: { kind: LegalKind; onExit: () => void }) {
  const { lang: appLang } = useLang();
  const [language, setLanguage] = useState<"vi" | "en">(appLang === "vi" ? "vi" : "en");
  const privacy = kind === "privacy";
  const title = privacy ? (language === "vi" ? "Chính sách quyền riêng tư" : "Privacy Policy") : language === "vi" ? "Điều khoản sử dụng" : "Terms of Service";
  const sections = privacy ? (language === "vi" ? PRIVACY_VI : PRIVACY_EN) : language === "vi" ? TERMS_VI : TERMS_EN;

  return (
    <main className="min-h-screen bg-[linear-gradient(145deg,#EAF8F5,#F7F3FF_55%,#FFF5DF)] p-4 text-[#463A31] sm:p-7">
      <div className="mx-auto max-w-[920px] overflow-hidden rounded-[30px] border-2 border-white bg-white/95 shadow-[0_12px_45px_rgba(55,70,70,.18)]">
        <header className="sticky top-0 z-10 flex flex-wrap items-center gap-3 border-b-2 border-[#E7E0D5] bg-white/95 px-4 py-4 backdrop-blur sm:px-7">
          <button onClick={onExit} className="grid h-11 w-11 place-items-center rounded-full bg-[#5C7BC9] text-white shadow-[0_4px_0_#435E9B]" aria-label={language === "vi" ? "Quay lại" : "Back"}><ArrowLeft /></button>
          <span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#DDF6F2] text-[#2E9B91]">{privacy ? <ShieldCheck /> : <FileText />}</span>
          <div className="min-w-0 flex-1"><h1 className="font-baloo text-xl font-extrabold sm:text-2xl">{title}</h1><p className="font-baloo text-xs font-semibold text-[#8B7D70]">{language === "vi" ? "Có hiệu lực" : "Effective"}: {LEGAL_EFFECTIVE_DATE}</p></div>
          <div className="flex rounded-xl bg-[#F1E9DC] p-1 font-baloo text-xs font-extrabold"><button onClick={() => setLanguage("vi")} className={`rounded-lg px-3 py-2 ${language === "vi" ? "bg-white text-[#D96C25] shadow-sm" : "text-[#88796B]"}`}>VI</button><button onClick={() => setLanguage("en")} className={`rounded-lg px-3 py-2 ${language === "en" ? "bg-white text-[#D96C25] shadow-sm" : "text-[#88796B]"}`}>EN</button></div>
        </header>
        <article className="space-y-6 px-5 py-7 sm:px-9">
          {sections.map((section) => <section key={section.title}><h2 className="mb-2 font-baloo text-lg font-extrabold text-[#3F7168]">{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph} className="mb-2 font-baloo text-sm font-semibold leading-7 text-[#62574D]">{paragraph}</p>)}{section.bullets && <ul className="list-disc space-y-2 pl-6 font-baloo text-sm font-semibold leading-6 text-[#62574D]">{section.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul>}</section>)}
          <a href={`mailto:${LEGAL_CONTACT_EMAIL}`} className="flex items-center gap-3 rounded-2xl border-2 border-[#CBEAE4] bg-[#EFFAF8] p-4 font-baloo text-sm font-extrabold text-[#287B72]"><Mail size={20} /> {LEGAL_CONTACT_EMAIL}</a>
        </article>
      </div>
    </main>
  );
}
